version: '3'

services:
  decaf_test_runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - ./rtests.sh
  
  decaf_validation_test_runner:
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      - ./assert_run.sh