name: Validation-Test

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Build docker images
        run: docker build -t validation-test .
      - name: Run validation test
        run: docker run -it validation-test ./assert_run.sh
